# Python Programlama Diline Giriş

Python programlama dili, bilgisayardaki herhangi bir işlemi gerçekleştirebileceğiniz bir yüksek seviye (high-level) programlama dilidir. İlk sürümü 1991 yılında ortaya çıkarılmıştır. Bugün, diğer programlama dillerine kıyasla görece yeni bir programlama dili olmasına rağmen C++ ve Java gibi dilleri sollayarak <a href="https://bootcamp.berkeley.edu/blog/most-in-demand-programming-languages/" target="_blank">en çok kullanılan 2. programlama dili olmuştur.</a> Ek olarak, herhangi bir kullanım ücreti yoktur.

Mühendislik dünyasında sıkça kullanılan MATLAB, kullanıcı dostu olmasının yanında ücretsiz bir yazılım değildir ( eğer bir öğrenci veya akademi hesabınız yoksa). Bu durumda Python dili, güçlü kütüphaneleriyle ve kullanıcı dostu bir programlama dili olmasıyla bugün yürütülen birçok mühendislik probleminde yoğun bir şekilde kullanılmaktadır.

Aynı şekilde sonlu elemanlar alanında da Python programlama diliyle geliştirilen çok güçlü çözücüler vardır ve geliştirmeleri sürekli devam etmektedir (Örnek: <a href="https://fenicsproject.org/FEniCSX" target="_blank">FEniCSx</a>). Bu derste Python programlama dilinin özelliklerine ve bazı örneklere değinmek derslerin anlaşılması açısından faydalı olacaktır.

## Eğitimde Kullanılabilecek Kütüphaneler

Sonlu elemanlar analizlerinde sıklıkla kullanılabilecek kütüphaneler **numpy**(matris, vektör oluşturma), **scipy**(sistem çözümleme) ve **matplotlib**(çözümü görselleştirme)** olarak sıralanabilir. 

### Numpy Kütüphanesi

Numpy ile denklem modellemelerinde kullanmak üzere hem vektör hem matrisler oluşturabiliriz. Öncelikle numpy kütüphanesini çağıralım;

In [32]:
import numpy as np

Şimdi 4 Elemandan oluşan bir vektör oluşturalım;

In [33]:
F = np.zeros(4)

`F` vektörünün İçindeki elemanlara bakmak için print fonksiyonunu kullanabiliriz;

In [34]:
print(F)

[0. 0. 0. 0.]


İstersek herhangi 2 sayı arasında eşit şekilde bölünmüş aralıklardan oluşan bir vektör de tanımlayabiliriz;

In [35]:
L = np.linspace(0,1,10)
print(L)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Şimdi de 2 boyutlu yapilara giriş olarak 4x4lük sıfırlardan oluşan bir F matrisi oluşturalım; 

In [36]:
K = np.zeros((4,4))
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Oluşturduğumuz matrisin diyagonal kısmını 1 rakamı ile dolduralım. Bunun için `for` döngüsü kullanabiliriz;

In [37]:
for indis in range(4):
    K[indis][indis] = 1
print(K)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Scipy Kütüphanesi
Scipy kütüphanesi bilimsel araştırmalarda sıklıkla kullanılan fonksiyonları içermektedir. Biz Scipy kütüphanesini oluşturacağımız lineer denklem sistemlerinin çözümü için kullanabiliriz. 

Aşağıdaki 4 bilinmeyenli 4 lineer denklem sistemini düşünelim;

$$a+b+c=70$$ 
$$a+b+d=80$$
$$a+b+d=75$$
$$b+c+d=70$$

Bu sistemi modellemek için yukarıda oluşturduğumuz `F` vektörü ve `K` matrisi kullanabiliriz. Bunun için öncelikle F vektörünü düzenleyelim;

In [38]:
F[0] = 75
F[1] = 80
F[2] = 75
F[3] = 70
print(F)

[75. 80. 75. 70.]


Burada dikkat etmemiz gereken bir husus olarak, Python'da indisler MATLAB'in aksine 1'den değil 0 rakamından başlar. Bu yüzden ilk elemana erişmek için her zaman 0 indisini kullanacağız. 

Şimdi `K` matrisini düzenleyelim. Öncelikle daha önce kısmen 1'lerle doldurduğumuz matrisi tekrar sıfırlayalım; 

In [39]:
K.fill(0)

Birinci denklem olan $$a+b+c=70$$
denkleminin sol tarafını modelleyecek şekilde `K` matrisinin ilk satırını değiştirelim;

In [40]:
K[0][0] = 1
K[0][1] = 1
K[0][2] = 1
K[0][3] = 0

Aynı işlemi diğer denklemler için de yapalım;

In [41]:
# İkinci denklem
K[1][0] = 1
K[1][1] = 1
K[1][2] = 0
K[1][3] = 1
# Üçüncü denklem
K[2][0] = 1
K[2][1] = 0
K[2][2] = 1
K[2][3] = 1
# Dördüncü denklem
K[3][0] = 0
K[3][1] = 1
K[3][2] = 1
K[3][3] = 1
print(K)

[[1. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]]


Artık denklem sistemini çözebiliriz. Bunun için scipy kütüphanesindeki <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html" target="_blank"> scipy.linalg.solve() </a> fonksiyonunu kullanabiliriz. Bunun için ilk önce fonksiyonu çağıralım; 

In [42]:
from scipy.linalg import solve

Çözüm vektörümüz `u` olsun. Şimdi matrisleri fonksiyonun içine yerleştirebiliriz;

In [43]:
u = solve(K,F)
print(u)

[30. 25. 20. 25.]


`u` vektörünün elemanları sırasıyla `a,b,c ve d` bilinmeyenlerini göstermektedir. Bulunan değerleri yerine koyarak çözümü kontrol edebilirsiniz.

### Matplotlib Kütüphanesi